Уровень 0
Придумайте матрицы, которые обладают следующими свойствами:
a) диагональная, ортогональная, но не единичная(!):
b) верхнетреугольная, ортогональная:
c) нижнетреугольная, ортогональная:
d) матрица, у которой определитель = 1, и все элементы не равны 0:
P.S. Во всех пунктах ответом должна быть ненулевая матрица размерности не менее 2!

Найдите собственные значения и собственные вектора матриц:
m = np.array([[2, 2],
[1, 3]])
print(m)

Уровень 1:
Найдите спектральное разложение матрицы:
m = np.array([[1, 2],
[2,3]])
print(m)

Постройте зависимость качества восстановления рукописных цифр (MNIST) в зависимости от различного количества компонент PCA. В качестве метрики различия предлагаю использовать MSE. *

У PCA есть метод transform и inverse_transofrm. Первый - снижает размерность, второй - восстанавливает оригинальные данные с потерей информации
Надо посчитать насколько в среднем точно восстанавливается оригинальная картинка в зависимости от количества компонент в PCA
В качестве справки можно использовать:

https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html - документация по PCA
https://scikit-learn.org/stable/modules/generated/sklearn.metrics.mean_squared_error.html  - документация по MSE
	
	Картинки цифр можно взять отсюда - https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_digits.html

In [1]:
import numpy as np

**a) диагональная, ортогональная, но не единичная**

In [18]:
#  Не смогла придумать другую диаганальную ортогональную матрицу, кроме как этой!

M1 = np.diag([-1, -1, -1])
M1

array([[-1,  0,  0],
       [ 0, -1,  0],
       [ 0,  0, -1]])

In [19]:
# Ортогональная - квадратная и произведение матрицы и транспонированнной к ней матрицы равно единичной.
T = M1.transpose() # получим такую же как исходная

In [20]:
E = np.dot(T,M1)
E

# Получили единичную матрицу. 

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [21]:
#матрица не вырожденна. Детерминант ортогональной матрицы равен 1 или -1
det_= np.linalg.det(M1)
det_

#  Верно!

-1.0

Полученная диагональная матрица является частным случаем треугольной матрицы и подходит к примеру b и c

**b) верхнетреугольная, ортогональная:**

**c) нижнетреугольная, ортогональная**

**d) матрица, у которой определитель = 1, и все элементы не равны 0**

In [27]:
from scipy.stats import ortho_group

In [124]:
m = ortho_group.rvs(dim=4)
m

array([[ 0.21139799,  0.50619533, -0.40359117, -0.73225088],
       [ 0.5045169 ,  0.47233356, -0.31952438,  0.64828071],
       [ 0.80595596, -0.55718062,  0.06587077, -0.1888009 ],
       [-0.22629311, -0.45849433, -0.85479786,  0.08885379]])

In [125]:
det_= np.linalg.det(m)
det_


1.0000000000000009

**Найдите собственные значения и собственные вектора матриц:**

In [127]:
m = np.array([[2, 2], [1, 3]]) 
print(m)

[[2 2]
 [1 3]]


In [128]:
w,v = np.linalg.eig(m)

In [132]:
for i in range(len(m)):
    print("Собственное значение " + str(w[i]))
    print("соответствующий ему собственный вектор" + str(v[:,i]))

Собственное значение 1.0
соответствующий ему собственный вектор[-0.89442719  0.4472136 ]
Собственное значение 4.0
соответствующий ему собственный вектор[-0.70710678 -0.70710678]


**Найдите спектральное разложение матрицы:**

In [166]:
# Спектральный анализ - это разложение матрицы на три : ортогональную S из собственных векторов и ее транспонированную,
#  диаганальную D из собственных значений
m = np.array([[1, 2], [2,3]])
print(m)

[[1 2]
 [2 3]]


In [171]:
w,v = np.linalg.eig(m) # вычислим собственные вектора и значения
print(f"Собственные значения: - {np.array(w)} " )
print("Собственные вектора:")
print(v)

Собственные значения: - [-0.23606798  4.23606798] 
Собственные вектора:
[[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]


In [172]:
#  Создаем диаганальную матрицу
D = np.diag(w)
D

array([[-0.23606798,  0.        ],
       [ 0.        ,  4.23606798]])

In [174]:
# создаем матрицу из собственных векторов ( у нас получилась симметричная)
S =v.T
S

array([[-0.85065081,  0.52573111],
       [-0.52573111, -0.85065081]])

In [175]:
# транспонированная форма S (будет совпадать)
S_t = S.T
S_t

array([[-0.85065081, -0.52573111],
       [ 0.52573111, -0.85065081]])

In [176]:
# проверим их ортогональность. Должны получить еденичную матрицу
np.dot(S_t,S)

array([[1., 0.],
       [0., 1.]])

In [177]:
 #   Проверим действительно ли полученные матрицы, являются спектральным разложение исходной матрицы 
np.dot(np.dot(S_t,D),S)

#  Мы получили исходную матрицу

array([[1., 2.],
       [2., 3.]])